### ISSUE TITLE
Unhandled IllegalStateException in DatadogInterceptor

### ISSUE THREAD

**Issue by neugartf** [DataDog/dd-sdk-android#1049]
**Describe what happened**
Hey peeps!

We are seeing quite a number of crashes that are indirectly triggered by the interceptor. 
See attached stack trace:
```
Fatal Exception: java.lang.IllegalStateException: closed
       at okio.RealBufferedSource.request(RealBufferedSource.kt:203)
       at okio.PeekSource.read(PeekSource.kt:50)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
       at okhttp3.Response.peekBody(Response.kt:197)
       at com.datadog.android.DatadogInterceptor.getBodyLength(DatadogInterceptor.kt:255)
       at com.datadog.android.DatadogInterceptor.handleResponse(DatadogInterceptor.kt:230)
       at com.datadog.android.DatadogInterceptor.onRequestIntercepted(DatadogInterceptor.kt:191)
       at com.datadog.android.tracing.TracingInterceptor.handleResponse(TracingInterceptor.kt:341)
       at com.datadog.android.tracing.TracingInterceptor.interceptAndTrace(TracingInterceptor.kt:215)
       at com.datadog.android.tracing.TracingInterceptor.intercept(TracingInterceptor.kt:148)
       at com.datadog.android.DatadogInterceptor.intercept(DatadogInterceptor.kt:174)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       ...
```
**Steps to reproduce the issue:**
We aren't able to reproduce this.

**Describe what you expected:**
No crash 🤷.

**Additional context**
- okhttp3 = '4.10.0'
- datadog = '1.13.0'

**Comment by xgouchet** [comment]
Hi @neugartf , and thanks for reporting this. We'll try and fix this asap. If you come across more details on the context where this happens, please let us know

**Comment by neugartf** [comment]
Thanks for the quick fix!
