### ISSUE TITLE
CICD failed due to Datadog

### ISSUE THREAD

**Issue by janakencora** [DataDog/dd-sdk-android#1064]
CICD is failing due to datadog sdk from yesterday

**Not able to generate the build**
from yesterday I am not able to generate the build.

**Error on bitrise:**
`Caused by: java.lang.NullPointerException: currentDir.parentFile must not be null
	at com.datadog.gradle.plugin.DdAndroidGradlePlugin.findDatadogCiFile(DdAndroidGradlePlugin.kt:272)
	at com.datadog.gradle.plugin.DdAndroidGradlePlugin.configureVariantForUploadTask$dd_sdk_android_gradle_plugin(DdAndroidGradlePlugin.kt:111)
	at com.datadog.gradle.plugin.DdAndroidGradlePlugin.apply$lambda-1$lambda-0(DdAndroidGradlePlugin.kt:46)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)`

**Additional context**
 - Datadog SDK version: 1.14.0

**Comment by janakencora** [comment]
It is working fine with 1.12.0

**Comment by 0xnm** [comment]
Hello @janakencora.

This is the issue not in `dd-sdk-android` library, but in our [Gradle plugin](https://plugins.gradle.org/plugin/com.datadoghq.dd-sdk-android-gradle-plugin). It is known and was already fixed in the latest version `1.5.1`. Please update the version you are using.

**Comment by janakencora** [comment]
Not found 1.5.1 version here in datadog
the last version I can see is 1.14.1

**Comment by 0xnm** [comment]
You should update the version of our Datadog Gradle plugin you are using, not the version of the Datadog SDK.

**Comment by 0xnm** [comment]
Hello @janakencora! I'm closing this issue due to inactivity. Feel free to re-open it if it still happens to you.
