### ISSUE TITLE
isSystemReady() modification for battery-less devices

### ISSUE THREAD

**Issue by GarryTransact** [DataDog/dd-sdk-android#1154]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to get the DataDog sdk running on an embedded device that doesn't use a battery (power supply only) and noticed it works only (i.e. uploads data) on an emulator of the app. Having done some digging I think the issue maybe the fact that the isSystemReady() call in the DataUploadRunnable class returns false. I placed a debugger on the call and noticed the battery related checks all return false (which makes sense) 
![image](https://user-images.githubusercontent.com/85942191/203314618-3df38698-41da-4894-876b-9375411c0e42.png)

I may simply be missing something but is there a flag that is set elsewhere for devices such as this?

**Describe the solution you'd like**
Configuration level item for disabling battery check.

**Comment by xgouchet** [comment]
Hi, this is an issue that can happen on some device that don't report correctly the information about the available power source (either power cord or battery). Our `isSystemReady()` is based on the following informations : 
- the battery (when present) is above 10%, or is charging (based on the `BatteryManager.EXTRA_STATUS` and `BatteryManager.EXTRA_LEVEL` of an `Intent.ACTION_BATTERY_CHANGED` broadcast message);
- the Power save mode is not enabled (based on the `PowerManager.isPowerSaveMode()` method);
- the device being plugged (based on the `BatteryManager.EXTRA_PLUGGED` of an `Intent.ACTION_BATTERY_CHANGED` broadcast message);

In your case, it's that last one that might report the wrong status. Can you add a breakpoint in the `BroadcastReceiverSystemInfoProvider` class, in the `onReceive()` method to see what values the extras of the received intents are?

**Comment by GarryTransact** [comment]
Having looked the value it a bit more it appears that 0 implies the device is actually on battery, and has a battery level of 0%, if I'm not mistaken. Sounds like we've got an issue on our side, possibly a missing feature or bug in our AOSP build for our device. @xgouchet appreciate your help and clarification, I'm going to look into what we can do on our side, I'm assuming there's not a workaround on the SDK side? 

Would it be possible for us to fork and make a local build? We're currently trialling DataDog on our device.

**Comment by xgouchet** [comment]
For now there's no workaround as this system check is there to prevent our SDK from impacting the battery life of the end users. 
This project is totally open sourced, so of course you can create a fork to remove this specific check indeed.

**Comment by GarryTransact** [comment]
That's great thanks @xgouchet , I have just one last question, do you have any documentation for how to build and publish locally? I did pull the sources and run an assemble all then import the dd-sdk-android aar artifact in locally, but ran into the below issues at runtime:

Appreciate this probably isn't a great forum for discussing runtime issues when building locally.

`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.blackboard.transact.slate, PID: 8146
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/lyft/kronos/AndroidClockFactory;
        at com.datadog.android.core.internal.CoreFeature.initializeClockSync(CoreFeature.kt:286)
        at com.datadog.android.core.internal.CoreFeature.initialize(CoreFeature.kt:176)
        at com.datadog.android.Datadog.initialize(Datadog.kt:94)
        at com.blackboard.transact.slate.application.SlateApplication.datadogConfig(SlateApplication.java:296)
        at com.blackboard.transact.slate.application.SlateApplication.onCreate(SlateApplication.java:276)
        at com.blackboard.transact.slate.application.SlateDebugApplication.onCreate(SlateDebugApplication.java:17)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:917)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lyft.kronos.AndroidClockFactory" on path: DexPathList[[zip file "/data/app/com.blackboard.transact.slate-fR96dZX1coY6oLMJIHYMZg==/base.apk"],nativeLibraryDirectories=[/data/app/com.blackboard.transact.slate-fR96dZX1coY6oLMJIHYMZg==/lib/arm, /data/app/com.blackboard.transact.slate-fR96dZX1coY6oLMJIHYMZg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.datadog.android.core.internal.CoreFeature.initializeClockSync(CoreFeature.kt:286) 
        at com.datadog.android.core.internal.CoreFeature.initialize(CoreFeature.kt:176) 
        at com.datadog.android.Datadog.initialize(Datadog.kt:94) 
        at com.blackboard.transact.slate.application.SlateApplication.datadogConfig(SlateApplication.java:296) 
        at com.blackboard.transact.slate.application.SlateApplication.onCreate(SlateApplication.java:276) 
        at com.blackboard.transact.slate.application.SlateDebugApplication.onCreate(SlateDebugApplication.java:17) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:917) `

**Comment by xgouchet** [comment]
So when you just build the `aar` and import it directly, instead of referencing the maven library, you lose the dependencies we use. Here are the dependencies that we use in the SDK, that you should also add to your project otherwise you'll hit mutliple `NoClassDefFoundError` : 
```
<dependencies>
    implementation("io.opentracing:opentracing-api:0.32.0")
    implementation("io.opentracing:opentracing-noop:0.32.0")
    implementation("io.opentracing:opentracing-util:0.32.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.6.10")
    implementation("com.squareup.okhttp3:okhttp:3.12.13")
    implementation("com.google.code.gson:gson:2.8.8")
    implementation("com.lyft.kronos:kronos-android:0.0.1-alpha11")
    implementation("androidx.core:core:1.3.1")
    implementation("androidx.navigation:navigation-fragment:2.3.0")
    implementation("androidx.navigation:navigation-runtime-ktx:2.3.0")
    implementation("androidx.recyclerview:recyclerview:1.1.0")
    implementation("androidx.work:work-runtime:2.7.0")
```

**Comment by GarryTransact** [comment]
Noticed that, I was able to do a local maven publish with the dependencies included etc... instead.
Just confirmed the logs are being pushed to our trial instance from our device, thanks again for all your help!

**Comment by xgouchet** [comment]
Glad you eventually got it working, let us know if we can help you further.
