### ISSUE TITLE
Runtime crash

### ISSUE THREAD

**Issue by clevertrevor** [DataDog/dd-sdk-android#144]
**Describe what happened**
Library was crashing shortly after app started twice. In my application class, after initializing Datadog and the loggers, I was logging two lines to each of my 3 Datadog loggers
Repeatable 100%. 

```
        DatadogLoggerManagerKt.getPaymentDatadogLogger().i(
                DatadogLoggerManagerKt.getPaymentDatadogLogger().successMessage());

        DatadogLoggerManagerKt.getPaymentDatadogLogger().e(
                DatadogLoggerManagerKt.getPaymentDatadogLogger().failureWithErrorCodeMessage());
        DatadogLoggerManagerKt.getEnrollmentDatadogLogger().e(
                DatadogLoggerManagerKt.getEnrollmentDatadogLogger().failureMessage());
        DatadogLoggerManagerKt.getEnrollmentDatadogLogger().i(
                DatadogLoggerManagerKt.getEnrollmentDatadogLogger().successMessage());
```
```
2020-02-20 15:22:03.203 E/AndroidRuntime: FATAL EXCEPTION: ddog
    Process: com.udemy.android, PID: 17968
    java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 312
        at java.util.Base64$Decoder.decode0(Base64.java:742)
        at java.util.Base64$Decoder.decode(Base64.java:526)
        at com.datadog.android.log.internal.file.LogFileReader.deobfuscateApi26(LogFileReader.kt:84)
        at com.datadog.android.log.internal.file.LogFileReader.deobfuscate(LogFileReader.kt:73)
        at com.datadog.android.log.internal.file.LogFileReader.readNextBatch(LogFileReader.kt:50)
        at com.datadog.android.log.internal.LogUploadRunnable.run(LogUploadRunnable.kt:33)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

My app has 3 Datadog loggers to allow for different service names.

Main code to create loggers
```
import com.datadog.android.log.Logger

interface LoggerMessages {
    fun successMessage(): String = "success"
    fun failureMessage(): String = "failure"
    fun failureWithErrorCodeMessage(): String = "failure: "
}

abstract class AbstractDatadogLogger(serviceName: String): LoggerMessages {

    private val datadogLogger = Logger.Builder()
            .setNetworkInfoEnabled(true)
            .setDatadogLogsEnabled(!BuildConfig.DEBUG)
            .setServiceName(serviceName)
            .build()

    // -- Below is copy of Datadog log API; forwards all logs to Datadog's logger

    /**
     * Sends a VERBOSE log message.
     * @param message the message to be logged
     * @param throwable a (nullable) throwable to be logged with the message
     * @param attributes a map of attributes to include only for this message. If an attribute with
     * the same key already exist in this logger, it will be overriden (just for this message)
     */
    @Suppress("FunctionMinLength")
    @JvmOverloads
    fun v(
            message: String,
            throwable: Throwable? = null,
            attributes: Map<String, Any?> = emptyMap()
    ) {
        datadogLogger.v(message, throwable, attributes)
    }

    /**
     * Sends a Debug log message.
     * @param message the message to be logged
     * @param throwable a (nullable) throwable to be logged with the message
     * @param attributes a map of attributes to include only for this message. If an attribute with
     * the same key already exist in this logger, it will be overriden (just for this message)
     */
    @Suppress("FunctionMinLength")
    @JvmOverloads
    fun d(
            message: String,
            throwable: Throwable? = null,
            attributes: Map<String, Any?> = emptyMap()
    ) {
        datadogLogger.d(message, throwable, attributes)
    }

    /**
     * Sends an Info log message.
     * @param message the message to be logged
     * @param throwable a (nullable) throwable to be logged with the message
     * @param attributes a map of attributes to include only for this message. If an attribute with
     * the same key already exist in this logger, it will be overriden (just for this message)
     */
    @Suppress("FunctionMinLength")
    @JvmOverloads
    fun i(
            message: String,
            throwable: Throwable? = null,
            attributes: Map<String, Any?> = emptyMap()
    ) {
        datadogLogger.i(message, throwable, attributes)
    }

    /**
     * Sends a Warning log message.
     * @param message the message to be logged
     * @param throwable a (nullable) throwable to be logged with the message
     * @param attributes a map of attributes to include only for this message. If an attribute with
     * the same key already exist in this logger, it will be overriden (just for this message)
     */
    @Suppress("FunctionMinLength")
    @JvmOverloads
    fun w(
            message: String,
            throwable: Throwable? = null,
            attributes: Map<String, Any?> = emptyMap()
    ) {
        datadogLogger.w(message, throwable, attributes)
    }

    /**
     * Sends an Error log message.
     * @param message the message to be logged
     * @param throwable a (nullable) throwable to be logged with the message
     * @param attributes a map of attributes to include only for this message. If an attribute with
     * the same key already exist in this logger, it will be overriden (just for this message)
     */
    @Suppress("FunctionMinLength")
    @JvmOverloads
    fun e(
            message: String,
            throwable: Throwable? = null,
            attributes: Map<String, Any?> = emptyMap()
    ) {
        datadogLogger.e(message, throwable, attributes)
    }

}

```

Concrete implementations are tiny. They only add to the interface with additional messages. sample usage is `logger.e(logger.errorMessage())`
see below for one of them
```
class EmailDatadogLogger : AbstractDatadogLogger("android.login.email"), EmailMessages

interface EmailMessages : LoggerMessages {
    override fun successMessage(): String = "email sign in success"
    override fun failureMessage(): String = "email sign in failure: "
    fun failureWithoutErrorCodeMessage(): String = "email sign in failure: generic, "
}
```

**Steps to reproduce the issue:**
Crashed on app start after the second app open (Application.onCreate() called again)
I can fix the issue by removing the lines above and reinstalling the app.

**Describe what you expected:**
lib to not crash

**Additional context**
 - Android OS version:8.1.0
 - Device Model:Mi Phone MI 8M1803E1A
 - Datadog SDK version:1.0.0
 - Versions of any other relevant dependencies (OkHttp, …): can provide if necessary
 - Proguard configuration: 6.2.0
 - Gradle Plugins:n/a

**Comment by mariusc83** [comment]
Hi @clevertrevor what version of the SDK are you using. We're not using obfuscation anymore at the FilePersistence level so I guess you are using an older version. Can you please update to our latest version **1.2.1** and let us know if we experience again the crash ?

**Comment by clevertrevor** [comment]
@mariusc83 1.2.1 fixed the issue. thanks for the quick response!
