### ISSUE TITLE
NullPointerException when finishing span

### ISSUE THREAD

**Issue by jamesbluecrow** [DataDog/dd-sdk-android#1569]
Thanks for taking the time for reporting an issue!

**Describe what happened**

```
Non-fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedList$Node java.util.LinkedList$Node.next' on a null object reference
       at java.util.LinkedList$ListItr.next(LinkedList.java:893)
       at com.datadog.opentracing.PendingTrace.expireReference(PendingTrace.java:192)
       at com.datadog.opentracing.PendingTrace.expireSpan(PendingTrace.java:118)
       at com.datadog.opentracing.PendingTrace.addSpan(PendingTrace.java:144)
       at com.datadog.opentracing.DDSpan.finishAndAddToTrace(DDSpan.java:101)
       at com.datadog.opentracing.DDSpan.finish(DDSpan.java:110)
       ...
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Steps to reproduce the issue:**
Not sure how to reproduce this. We have only seen 10 instances of this so far.

**Describe what you expected:**

**Additional context**
 - Android OS version: See in Android 11, 12 & 13
 - Device Model: `HOT Play`, `Galaxy S21 FE 5G`, `Galaxy A31`, `Model:Vivo 1907_19`, `Galaxy Z Fold4`, `Model:Pixel 7`, `OnePlus 11 5G`...
 - Datadog SDK version: `1.19.2`
 - Versions of any other relevant dependencies (OkHttp, …):  `OkHttp=4.11.0` 
 - Proguard configuration: 
 - Gradle Plugins:

**Comment by xgouchet** [comment]
Hi @jamesbluecrow, can you show us a sample code on how you're using the tracing feature of the SDK?

**Comment by jamesbluecrow** [comment]
> Hi @jamesbluecrow, can you show us a sample code on how you're using the tracing feature of the SDK?

@xgouchet We have something like the code below:

```
override fun track(event: (PerformanceEvent)) {
    runAndCatch {
        val tracer = GlobalTracer.get()
        when (event) {
            is PerformanceEvent.Start -> {
                val parentSpan = event.context.parentId?.let { parentId ->
                    contextToSpanMap[parentId]
                }

                // Parent may not exist or not have been tracked. If so we ignore it for creating the span.
                if (parentSpan == null) {
                    val spanBuilder = tracer.buildSpan(event.context.name)
                    for ((key, value) in event.context.tags) {
                        spanBuilder.withTag(key, value)
                    }
                    val span = spanBuilder.start()
                    contextToSpanMap.put(event.context.id, PerformanceSpan(event.context, span))
                } else {
                    val parentScope = tracer.activateSpan(parentSpan.span)
                    parentScope.use {
                        val spanBuilder = tracer.buildSpan(event.context.name)
                        for ((key, value) in event.context.tags) {
                            spanBuilder.withTag(key, value)
                        }

                        val childSpan = spanBuilder.start()
                        contextToSpanMap.put(
                            event.context.id,
                            PerformanceSpan(event.context, childSpan),
                        )
                    }
                }
            }

            is PerformanceEvent.End -> {
                val span = contextToSpanMap[event.context.id]!!
                span.span.finish()
                contextToSpanMap.remove(event.context.id)
            }
        }
    }
}
```

I'm wondering if somehow it could be that we try to finish a span that has already been finished?

**Comment by xgouchet** [comment]
Indeed it might be that. If you cast the span to the class `DDSPan`, there is an `isFinished()` method that you can use to check if it's already finished.

**Comment by jamesbluecrow** [comment]
> Indeed it might be that. If you cast the span to the class `DDSPan`, there is an `isFinished()` method that you can use to check if it's already finished.

We added some code like:

```
if (!span.isFinished) {
    span.finish()
}
```

but unfortunately it doesn't seem to be that doesn't seem to be the root cause because we see some exceptions.

**Comment by jamesbluecrow** [comment]
Any updates on this @xgouchet ?

We've seen it happening more than 500 times and I suspect that it is related to concurrency as well as the other issue.

It happens from the trace interceptor mostly:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedList$Node java.util.LinkedList$Node.next' on a null object reference
       at java.util.LinkedList$ListItr.next(LinkedList.java:893)
       at com.datadog.opentracing.PendingTrace.expireReference(PendingTrace.java:192)
       at com.datadog.opentracing.PendingTrace.expireSpan(PendingTrace.java:118)
       at com.datadog.opentracing.PendingTrace.addSpan(PendingTrace.java:144)
       at com.datadog.opentracing.DDSpan.finishAndAddToTrace(DDSpan.java:101)
       at com.datadog.opentracing.DDSpan.finish(DDSpan.java:110)
       at com.datadog.android.tracing.TracingInterceptor.handleResponse(TracingInterceptor.kt:514)
       at com.datadog.android.tracing.TracingInterceptor.interceptAndTrace(TracingInterceptor.kt:248)
       at com.datadog.android.tracing.TracingInterceptor.intercept(TracingInterceptor.kt:180)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.openphone.network.retrofit.interceptor.DatadogSpanInterceptor.intercept(DatadogSpanInterceptor.kt:31)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

What makes me suspect it is also related to concurrency is this other exception that has popped up recently:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
       at java.util.LinkedList.toArray(LinkedList.java:1057)
       at java.util.ArrayList.<init>(ArrayList.java:191)
       at com.datadog.opentracing.DDTracer.write(DDTracer.java:305)
       at com.datadog.opentracing.PendingTrace.write(PendingTrace.java:210)
       at com.datadog.opentracing.PendingTrace.expireReference(PendingTrace.java:183)
       at com.datadog.opentracing.PendingTrace.expireSpan(PendingTrace.java:118)
       at com.datadog.opentracing.PendingTrace.addSpan(PendingTrace.java:144)
       at com.datadog.opentracing.DDSpan.finishAndAddToTrace(DDSpan.java:101)
       at com.datadog.opentracing.DDSpan.finish(DDSpan.java:110)
       at com.datadog.android.okhttp.trace.TracingInterceptor.handleThrowable(TracingInterceptor.kt:597)
       at com.datadog.android.okhttp.trace.TracingInterceptor.interceptAndTrace(TracingInterceptor.kt:304)
       at com.datadog.android.okhttp.trace.TracingInterceptor.intercept(TracingInterceptor.kt:216)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.openphone.thirdparty.datadog.DatadogSpanInterceptor.intercept(DatadogSpanInterceptor.kt:31)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by jamesbluecrow** [comment]
> Hi did you upgrade to version `2.2.0`? We made [changes](https://github.com/DataDog/dd-sdk-android/pull/1623) to make the `PendingTrace` thread safe, which should avoid this issue as well

Oh cool, good to know. We recently upgraded to `2.2.0` but we haven't released it yet. I'll keep an eye and come back to you if we don't see this issue anymore.

Thanks for the update and for the effort trying to fix it 🙏

**Comment by 0xnm** [comment]
Hello @jamesbluecrow! Do you have any update on the issue? Does it still happen?

**Comment by jamesbluecrow** [comment]
Sorry I never came back to update this. I haven't seen any instance of this issue since we updated to 2.2.0.

Thanks for the fix folks 🙏
