### ISSUE TITLE
Report - The environment name should contain maximum 196... In this case the Datadog SDK will not be initialised.

### ISSUE THREAD

**Issue by nicolasjafelle** [DataDog/dd-sdk-android#1610]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Our Datadog SDK android it showing some incosistency errors while using Google Play to build and deploy our apps with AAB format. We are not able to reproduce this issue locally in our devices or in emulators. 
We are using Jetpack Startup 1.1.1 that maybe could be relate or not: https://developer.android.com/jetpack/androidx/releases/startup

Stacktrace is:
```
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalArgumentException: The environment name should contain maximum 196 of the following allowed characters [a-zA-Z0-9_:./-] and should never finish with a semicolon.In this case the Datadog SDK will not be initialised.
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Caused by: androidx.startup.StartupException: java.lang.IllegalArgumentException: The environment name should contain maximum 196 of the following allowed characters [a-zA-Z0-9_:./-] and should never finish with a semicolon.In this case the Datadog SDK will not be initialised.
        at androidx.startup.AppInitializer.doInitialize(AppInitializer:187)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer:238)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer:206)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider:45)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Caused by: java.lang.IllegalArgumentException: The environment name should contain maximum 196 of the following allowed characters [a-zA-Z0-9_:./-] and should never finish with a semicolon.In this case the Datadog SDK will not be initialised.
```

**Additional context**
 - Android OS version: 29-30-33
 - Device Model: Google Mainline, Samsung s20, Motorola one Action, Motorola Edge 30
 - Datadog SDK version: 2.0.0-beta3
 - Proguard configuration: yes
 - Gradle Plugins: nop

**Comment by xgouchet** [comment]
Hi @nicolasjafelle , and thanks for opening this ticket. 

Can you tell us what `env` value you're using to initialise the SDK (the `env` parameter in the `Configuration.Builder` constructor)? It seems like the value you're providing doesn't match the accepted format

**Comment by nicolasjafelle** [comment]
@xgouchet Hey! Thank you so much for your quick response. I was able to fix it on my side. I was actually using `""` as an `env` variable name in our release process. So in terms of `Datadog` the issue and the message was correct just a litte confuse when talking about `environment` and `env` maybe a more user friendly developer message could be:
```
The env value in your Configuration object cannot be an empty String and should contain maximum 196 of the following allowed characters [a-zA-Z0-9_:./-] and should never finish with a semicolon. In this case the Datadog SDK will not be initialised.
```
Thank you so much for your help!!

**Comment by xgouchet** [comment]
Thanks for your answer, indeed the message should be more explicit, we'll fix that shortly. It's weird though that the stacktrace you copied didn't mention the call to `Datadog.initialize()`
