### ISSUE TITLE
UploadWorker Canceled

### ISSUE THREAD

**Issue by ichsanachmad** [DataDog/dd-sdk-android#1814]
**Describe what happened**
my datadog got this issue, so my log is not captured

```
Work [ id=xx, tags={ com.datadog.android.core.internal.data.upload.UploadWorker, DatadogBackgroundUpload } ] was cancelled
java.util.concurrent.CancellationException: Task was cancelled.
  at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
  at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
  at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
  at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
  at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
  at java.lang.Thread.run(Thread.java:1012)
```
**Steps to reproduce the issue:**
Intermittent issue when send log is not showing on datadog dashboard (logs)

**Describe what you expected:**
It should be showing and captured

**Additional context**
 - Android OS version: Android API 21
 - Device Model: Android Emulator
 - Datadog SDK version: 2.3.0
 - Versions of any other relevant dependencies (OkHttp, …): -
 - Proguard configuration: -
 - Gradle Plugins: 7.3.1

**Comment by 0xnm** [comment]
Hello @ichsanachmad! It is not quite clear what is the issue you have. Do you mean that you cannot see any data sent by Android SDK in the Datadog dashboard? If yes, can you please share your setup snippet and make sure that you configured SDK to use the right datacenter?

**Comment by ichsanachmad** [comment]
some of my log not showing in the dashboard sir @0xnm

**Comment by 0xnm** [comment]
@ichsanachmad Please provide the SDK setup code snippet and tell which datacenter you are using. Also if only __some__ logs are missing, is it possible for you to identify the common pattern for the logs which are missing?

You may want also to set SDK logcat verbosity to `DEBUG` by calling `Datadog.setVerbosity(Log.DEBUG)` in order to explore the logcat for the messages from our SDK.

**Comment by ichsanachmad** [comment]
i'm using EU1 data center, here's my setup


```
        if (Datadog.isInitialized()) {
            Datadog.stopInstance()
        }
        isConvertKeyToCamelCase = autoConvertKeyToCamelCase
        val envName = prefs.getAppEnvironment()

        val datadogConfig = Configuration.Builder(
            clientToken = clientToken,
            env = envName,
            service = prefs.getAppName(),
        )
            .setCrashReportsEnabled(true)
            .useSite(datadogSite)
            .build()

        Datadog.initialize(
            context = context,
            configuration = datadogConfig,
            trackingConsent = TrackingConsent.GRANTED,
        )

        val logsConfig = LogsConfiguration.Builder().build()
        Logs.enable(logsConfig)

        datadogLogger = Logger.Builder()
            .setNetworkInfoEnabled(true)
            .setService(prefs.getAppName())
            .setLogcatLogsEnabled(true)
            .setBundleWithTraceEnabled(true)
            .setBundleWithRumEnabled(enableRum)
            .setName(prefs.getAppName())
            .build()

        if (isConvertKeyToCamelCase) {
            datadogLogger?.addTag(AttributeKeyCamelCase.APP_NAME.key, prefs.getAppName())
            datadogLogger?.addTag(AttributeKeyCamelCase.APP_ID.key, prefs.getAppId())
        } else {
            datadogLogger?.addTag(AttributeKeySnakeCase.APP_NAME.key, prefs.getAppName())
            datadogLogger?.addTag(AttributeKeySnakeCase.APP_ID.key, prefs.getAppId())
        }

        if (enableRum) {
            GlobalRumMonitor.get()
            Rum.enable(
                rumConfiguration = RumConfiguration
                    .Builder(applicationId)
                    .trackUserInteractions()
                    .trackLongTasks()
                    .trackBackgroundEvents(true)
                    .useViewTrackingStrategy(MixedViewTrackingStrategy(true))
                    .build(),
            )
        }
```

**Comment by 0xnm** [comment]
@ichsanachmad Thanks for posting setup snippet. It looks okay, but I have few questions:

* What is the purpose of calling `Datadog.stopInstance`? Do you setup Datadog SDK in the `Application#onCreate`?
* What is the purpose of calling `GlobalRumMonitor.get()` and not using the return value? Anyway, it should be called only after RUM is enabled.

Do you see any pattern for the expected logs not showing up in the Datadog dashboard? Like maybe logs when application is in the background, etc.

What is the volume of the logs not showing up? Is it minority or majority of the logs sent?

Do you see any warnings/errors in the Logcat (apart of the stacktrace you've posted originally) if you set `Datadog.setVerbosity(Log.DEBUG)` when initializing the SDK?

**Comment by ichsanachmad** [comment]
after i do some changes in the way init, i think everything run as expected by changing init call to `Application#onCreate` sir,  @0xnm but some of majority logs missing, the pattern is like custom log and somethings like okhttp log is showing up, but still some of majority log still missing

**Comment by 0xnm** [comment]
Unfortunately it is still not clear what is the pattern for the logs missing, given that some of them are in fact sent. If you don't see any warnings/errors in the Logcat from Datadog SDK, all of them should be delivered (the stacktrace in the original message should have no impact).

If you want us to analyze the data on the Dashboard side, you can open a ticket using the channels provided [here](https://www.datadoghq.com/support/), specifying your Org details and referencing this issue.

**Comment by 0xnm** [comment]
Hello @ichsanachmad! I'm closing this issue due to inactivity. If you have more questions, don't hesitate to reopen it.
