### ISSUE TITLE
./gradlew uploadMappingRelease crashes trying to upload mapping.txt file after release build

### ISSUE THREAD

**Issue by tomdiz-epicorebiosystems** [DataDog/dd-sdk-android#2016]
### Stack trace

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.datadog.gradle.plugin.internal.OkHttpUploader
        at com.datadog.gradle.plugin.DdFileUploadTask.<init>(DdFileUploadTask.kt:35)
        at com.datadog.gradle.plugin.DdMappingFileUploadTask.<init>(DdMappingFileUploadTask.kt:23)
        at com.datadog.gradle.plugin.DdMappingFileUploadTask_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2097)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:524)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:88)
        ... 173 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class okhttp3.MediaType does not have member field 'okhttp3.MediaType$Companion Companion' [in thread "Daemon worker Thread 29"]
        at com.datadog.gradle.plugin.internal.OkHttpUploader.<clinit>(OkHttpUploader.kt:276)
        ... 182 more

### Reproduction steps

Running following command in Terminal window:

./gradlew uploadMappingRelease

### Volume

100

### Affected SDK versions

1.13.1

### Latest working SDK version

1.13.1

### Does the crash manifest in the latest SDK version?

Yes

### Kotlin / Java version

Java 1.8

### Gradle / AGP version

Gradle version 8.4

### Other dependencies versions

I'm using ktor 2.3.6 in my application.

### Device Information

Terminal window mapping.txt file upload

**Comment by tomdiz-epicorebiosystems** [comment]
My gradle file contains:

plugins {
    id("com.datadoghq.dd-sdk-android-gradle-plugin") version "1.13.1"
    id("org.jetbrains.kotlin.plugin.serialization") version "1.9.10"    // NOTE: This needs to match kotlin version
}

At the bottom of my gradle file is:

datadog {
    site = "US5"
}

**Comment by tomdiz-epicorebiosystems** [comment]
Wrong SDK
