### ISSUE TITLE
Crash on DdRumContentProvider caused by java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by NFesquet** [DataDog/dd-sdk-android#2139]
### Stack trace

          Caused by java.lang.ClassNotFoundException: Didn't find class "com.datadog.android.rum.DdRumContentProvider" on path: DexPathList[[zip file "/data/app/sport.android.betclic.ci-nHfrwQQzvWNk3Ju2pmXEuw==/base.apk"],nativeLibraryDirectories=[/data/app/sport.android.betclic.ci-nHfrwQQzvWNk3Ju2pmXEuw==/lib/arm64, /data/app/sport.android.betclic.ci-nHfrwQQzvWNk3Ju2pmXEuw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
       at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8165)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7717)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7581)
       at android.app.ActivityThread.access$2600(ActivityThread.java:260)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### Reproduction steps

Could not reproduce locally, only happens in background, on certain Android 10 devices.

Same issue as https://github.com/DataDog/dd-sdk-android/issues/1584

### Volume

Hard to tell, depends on the device

### Affected SDK versions

2.10.0

### Latest working SDK version

1.11.1

### Does the crash manifest in the latest SDK version?

Yes

### Kotlin / Java version

1.9.22

### Gradle / AGP version

Gradle 8.3.2 / AGP 8.3.0

### Other dependencies versions

okhttp 4.9.3

### Device Information

100% Android 10
100% background
Only affects certain devices : mainly Transsion (Smart, Smart HD, Spark 4, Spark 5 Pro), some Huawei (P30 Lite, P30 Pro), some Samsung (Galaxy S9, S9+), some Xiaomi (Redmi Not 9)

**Comment by xgouchet** [comment]
Hi @NFesquet , thanks a lot for opening this issue.
I'll close it here and reopen the #1584 to keep all the discussion in the same place.

**Comment by xgouchet** [comment]
Hi @NFesquet , 

Are you publishing your application via an APK or App Bundle ? If you rename the `*.apk`/ `*.aab` and look for the `classes.dex` file with the dex2jar tool, to check for the presence of the  `com.datadog.android.rum.DdRumContentProvider`

Also, can you try making sure that all the Datadog libraries you're using are using the same version in your app?
