### ISSUE TITLE
Support of newer okHttp versions

### ISSUE THREAD

**Issue by nf3lix** [DataDog/dd-sdk-android#221]
**Describe what happened**
If I use a newer SDK version than 1.1.1, it is not possible for me to use a current version of OkHttp. During the initialisation of Datadog the following error occurs:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.datadogtestapp, PID: 8047
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)
        at okhttp3.CipherSuite.<clinit>(CipherSuite.java:49)
        at okhttp3.ConnectionSpec.<clinit>(ConnectionSpec.java:51)
        at com.datadog.android.Datadog.buildOkHttpClient(Datadog.kt:267)
        at com.datadog.android.Datadog.setupLogsUploader(Datadog.kt:300)
        at com.datadog.android.Datadog.initialize(Datadog.kt:134)
        at com.example.datadogtestapp.ItemListActivity.onCreate(ItemListActivity.kt:27)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Activity.performCreate(Activity.java:7979)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3477)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
```

This behaviour might be caused by the downgrade of OkHttp in the DD SDK version 1.2.0 

**Steps to reproduce the issue:**
- Add the following dependencies:
`implementation 'com.squareup.okhttp3:okhttp:3.14.0'` (newer version than 3.12.10)
`implementation 'com.datadoghq:dd-sdk-android:1.3.0'` (newer version than 1.1.1)
- Add "Datadog.initialize" statement to your code and try to run the app

**Describe what you expected:**
I expected to be able to use newer OkHttp versions than OkHttp 3.12.10. Is it possible to support those SDKs in future versions again or is there a secure way to work around this conflict?

**Additional context**
 - Android OS version: 8.1
 - Device Model: Nexus 5X
 - Datadog SDK version: 1.3.0
 - other dependencies: 
```
implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'androidx.core:core-ktx:1.2.0'
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'androidx.recyclerview:recyclerview:1.1.0'
implementation 'com.google.android.material:material:1.1.0'
implementation 'com.squareup.okhttp3:okhttp:3.14.0'
implementation 'com.datadoghq:dd-sdk-android:1.3.0'
```

 - Proguard configuration: 
 - Gradle Plugins:

**Comment by xgouchet** [comment]
Hi @nf3lix and thanks for reporting this issue. 

The OkHttp version 3.12.10 is the latest one with support for API 19 (cf [OkHttp 3 changelog](https://square.github.io/okhttp/changelog_3x/#version-3130)). 
Because some of our customers still need to support older versions of Android, we unfortunately can't bump our version of OkHttp up.

Regarding the issue you're facing, we'll investigate to find if a workaround is possible. I'll keep you posted ASAP.

**Comment by xgouchet** [comment]
Ok spotted the issue. 
In addition to dropping support of low Android APIs, it also drops support of Java 7, meaning that in OkHttp version `3.13.0` and hight, features of the java 8 language are used (in this case, java lambda functions).

You need to tell the Android compiler that your project is using features from Java 8, so that it handles those properly. More precisely, in your application's `build.gradle`, you need to add the following code : 

```groovy
android {
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

kotlinOptions {
    jvmTarget = "1.8"
}
```

**Comment by nf3lix** [comment]
Works for me, thanks!
