### ISSUE TITLE
Fatal Exception: java.io.FileNotFoundException /data/user/0/com.activehours/files/dd-logs-v1/1600303496930 (Permission denied) com.datadog.android.core.internal.data.file.FileExtensionsKt.readBytes

### ISSUE THREAD

**Issue by ronak-earnin** [DataDog/dd-sdk-android#377]
We are seeing a huge spike in crashes happening due to DataDog. Please see the following details: 

**Describe what happened**
Include any error message or stack trace if available.
Stacktrace:
```
Fatal Exception: java.io.FileNotFoundException: /data/user/0/com.activehours/files/dd-logs-v1/1600303496930 (Permission denied)
       at java.io.FileInputStream.open0(FileInputStream.java)
       at java.io.FileInputStream.open(FileInputStream.java:200)
       at java.io.FileInputStream.<init>(FileInputStream.java:150)
       at com.datadog.android.core.internal.data.file.FileExtensionsKt.readBytes(FileExtensions.kt:7)
       at com.datadog.android.core.internal.data.file.FileReader.readNextFile(FileReader.kt:74)
       at com.datadog.android.core.internal.data.file.FileReader.readNextBatch(FileReader.kt:29)
       at com.datadog.android.core.internal.data.upload.DataUploadRunnable.run(DataUploadRunnable.kt:36)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

It has happened 385 times in last 30 days.

**Steps to reproduce the issue:**
Not able to reproduce.

**Describe what you expected:**

**Additional context**
 - Android OS version: Android 9 (74% of times)
 - Device Model: Motorola devices (100% of times)
 - Datadog SDK version: 1.4.3
- Device state: Background (95% times)

**Comment by xgouchet** [comment]
Hi, thanks for raising this issue, 

This is weird bug, as the SDK did get the permission to write the file but can't read it. Anyway we are working on a fix and will publish it really soon.

**Comment by xgouchet** [comment]
Hi again @ronak-earnin , 
this bug should be fixed in the latest version of the SDK (version `1.5.2`). Let us know if that works for you, or if you encounter any other issue.

**Comment by ronak-earnin** [comment]
Hi @xgouchet, a fix in version `1.5.2` sounds great. We will update to it and see if this is happening again. Thanks a lot.

**Comment by xgouchet** [comment]
Hello @ronak-earnin , 

have you been able to update to `1.5.2`. Did it fix the issue ?

**Comment by ronak-earnin** [comment]
Hi @xgouchet,  we have updated to 1.5.2 and shipped it recently. Once we have more data, I can let you know.

**Comment by xgouchet** [comment]
Hello @ronak-earnin, is this issue still present with the latest versions of the SDK?

**Comment by ronak-earnin** [comment]
This is no longer an issue. Thank you for all your help.
