### ISSUE TITLE
Prevent Multiple Calls To Initialize

### ISSUE THREAD

**Issue by Vavassor** [DataDog/dd-sdk-android#86]
I'm using Roboelectric for android unit tests. This [calls Application#onCreate every test](https://github.com/robolectric/robolectric/issues/3108) and has an unfortunate interaction with this library. It causes `Datadog.initialize` to be called multiple times. So every test in the suite fails.

I have a workaround by manually tracking whether it's initialized. However, it could be helpful to have a method like `Datadog.isInitialized` to tell whether `Datadog.initialize` can be called safely.

Or, a method like `Datadog.setInTestMode`. [SoLoader](https://github.com/facebook/SoLoader) (another library that I had issues with) uses this strategy and has `SoLoader.setInTestMode`. I think the idea with this is you can call it in the test runner instead of modifying the `Application`.

The error:
```
java.lang.IllegalStateException: Datadog has already been initialized.
	at com.datadog.android.Datadog.initialize(Datadog.kt:94)
	at com.datadog.android.Datadog.initialize$default(Datadog.kt:92)
	at com.datadog.android.Datadog.initialize(Datadog.kt)
	at com.aapmobileedb.MainApplication.onCreate(MainApplication.java:62)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:276)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:276)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xgouchet** [comment]
Thanks for reporting this issue Andrew, that's indeed something we'll be fixing in the near future.
