### ISSUE TITLE
com.datadog.android.rum.internal.anr.ANRException: Application Not Responding

### ISSUE THREAD

**Issue by akshay321max** [DataDog/dd-sdk-android#984]
Facing application Crash due to DataDog. Please resolve this.

SDK version: 1.10.0
Android OS version : 7.0
Device : Samsung s6

com.datadog.android.rum.internal.anr.ANRException
	at android.content.res.ApkAssets.getStringFromPool(ApkAssets.java:135)
	at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:759)
	at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1273)
	at android.content.res.TypedArray.getValueAt(TypedArray.java:1260)
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:544)
	at android.widget.TextView.readTextAppearance(TextView.java:3887)
	at android.widget.TextView.<init>(TextView.java:1223)
	at android.widget.Button.<init>(Button.java:181)
	at android.widget.CompoundButton.<init>(CompoundButton.java:103)
	at android.widget.CheckBox.<init>(CheckBox.java:69)
	at android.widget.CheckBox.<init>(CheckBox.java:65)
	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:3)
	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:2)
	at androidx.appcompat.app.AppCompatViewInflater.createCheckBox(AppCompatViewInflater.java:1)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:20)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:19)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
	at com.cbre.myreceipts.adapter.SelectedImagesAdapter.onCreateViewHolder(SelectedImagesAdapter.kt:3)
	at com.cbre.myreceipts.adapter.SelectedImagesAdapter.onCreateViewHolder(SelectedImagesAdapter.kt:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.g(RecyclerView.java:100)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.b(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.t(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.m(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:64)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:12)
	at android.view.View.measure(View.java:24964)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:24964)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:24964)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:24964)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:24964)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:24964)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7149)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1036)
	at android.view.View.measure(View.java:24964)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3382)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2098)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2397)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1958)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8636)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
	at android.view.Choreographer.doCallbacks(Choreographer.java:765)
	at android.view.Choreographer.doFrame(Choreographer.java:700)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
	
When I am opening application getting above error and application crashing again and again
Please solve this issue ASAP

**Comment by xgouchet** [comment]
Hi, the above stack trace corresponds to our ANR detection mecanism, and in theory should not crash your application. The way we do it is that we observe the stack trace blocking the main thread of your application. In your case this is some code going through the following method: 

```
at com.cbre.myreceipts.adapter.SelectedImagesAdapter.onCreateViewHolder(SelectedImagesAdapter.kt:3)
```

Are you seeing the application crash or are those just errors appearing in your Datadog dashboards? If you do see the app crashing with this stacktrace, can you send us a minimal sample code reproducing the issue?

**Comment by akshay321max** [comment]
Hello @xgouchet.  i am facing an application crash. I see the logs are coming in datadog which are above mentioned.

**Comment by akshay321max** [comment]
Thank you very much for your response I found the issue is with some other method.
